vaadin.launch-browser=true
spring.application.name=Sistema-Gestor-Personas

# ========== PostgreSQL ==========
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== MongoDB ==========
spring.mongodb.uri=mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:db_mongo}

# ========== Redis ==========
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
# spring.data.redis.password=${REDIS_PASSWORD:}

# ========== Server ==========
server.port=${SERVER_PORT:8080}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true